version: "3"

tasks:
  build-image:packer:
    internal: true
    dir: ./packer/{{.DIR}}
    cmds:
      - packer init . && packer build .

  build:packer:base:
    cmds:
      - task: build-image:packer
        vars:
          DIR: base
    sources:
      - ./packer/base/**

  build:packer:docker:
    deps:
      - build:packer:base
    cmds:
      - task: build-image:packer
        vars:
          DIR: docker
    sources:
      - ./packer/docker/**

  build:packer:hashi:
    deps:
      - build:packer:docker
    cmds:
      - task: build-image:packer
        vars:
          DIR: hashi
    sources:
      - ./packer/hashi/**

  build:packer:tools:
    deps:
      - build:packer:hashi
    cmds:
      - task: build-image:packer
        vars:
          DIR: tools
    sources:
      - ./packer/tools/**

  build:packer:dotfiles:
    deps:
      - build:packer:tools
    cmds:
      - task: build-image:packer
        vars:
          DIR: dotfiles
    sources:
      - ./packer/dotfiles/**

  build:packer:all:
    deps:
      - build:packer:dotfiles
    sources:
      - ./packer/**/*