version: "3"

  
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    cmds:
      - task --list-all

  build-image:packer:
    internal: true
    dir: ./packer/{{.DIR}}
    cmds:
      - packer init . && packer build .

  build:packer:base:
    cmds:
      - task: build-image:packer
        vars:
          DIR: base
    sources:
      - ./packer/base/**

  build:packer:docker:
    deps:
      - build:packer:base
    cmds:
      - task: build-image:packer
        vars:
          DIR: docker
    sources:
      - ./packer/docker/**

  build:packer:hashi:
    deps:
      - build:packer:docker
    cmds:
      - task: build-image:packer
        vars:
          DIR: hashi
    sources:
      - ./packer/hashi/**

  build:packer:tools:
    deps:
      - build:packer:hashi
    cmds:
      - task: build-image:packer
        vars:
          DIR: tools
    sources:
      - ./packer/tools/**

  build:packer:personal:
    deps:
      - build:packer:tools
    cmds:
      - task: build-image:packer
        vars:
          DIR: personal
    sources:
      - ./packer/personal/**

  build:packer:all:
    deps:
      - build:packer:personal
    sources:
      - ./packer/**/*

  push:hub:
    deps:
      - build:packer:all
    cmds:
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      - docker tag reg.slab.lan:5000/devbox-tools:latest $DOCKERHUB_USER/devbox:tools
      - docker tag reg.slab.lan:5000/devbox-personal:latest $DOCKERHUB_USER/devbox:$DOCKERHUB_TAG
      - docker tag reg.slab.lan:5000/devbox-personal:latest $DOCKERHUB_USER/devbox:latest
      - docker push $DOCKERHUB_USER/devbox:tools
      - docker push $DOCKERHUB_USER/devbox:$DOCKERHUB_TAG
      - docker push $DOCKERHUB_USER/devbox:latest